# Generated by Django 3.2.3 on 2021-06-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('final', models.TimeField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='horario_atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('atractivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Atractivos.atractivo')),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Atractivos.horario')),
            ],
        ),
        migrations.AddField(
            model_name='atractivo',
            name='categorias',
            field=models.ManyToManyField(to='Atractivos.Categoria'),
        ),
        migrations.AddField(
            model_name='atractivo',
            name='servicios',
            field=models.ManyToManyField(to='Atractivos.Servicio'),
        ),
        migrations.AddField(
            model_name='atractivo',
            name='tipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Atractivos.tipo'),
        ),
        migrations.AddField(
            model_name='atractivo',
            name='zona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Atractivos.zona'),
        ),
    ]
