# Generated by Django 3.2.4 on 2021-06-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atractivos', '0002_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.AddField(
            model_name='atractivo',
            name='direccion',
            field=models.CharField(default='no registrado', max_length=100),
        ),
    ]
