# Generated by Django 3.2.4 on 2021-06-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atractivos', '0003_auto_20210605_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivo',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
